/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.foodcitymanagement.view;

import com.foodcitymanagement.controller.ItemController;
import com.foodcitymanagement.dto.Item;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class ItemManageForm extends javax.swing.JFrame {

    /**
     * Creates new form ItemManageForm
     */
    public ItemManageForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnDelete = new javax.swing.JButton();
        txtItemQunti = new javax.swing.JTextField();
        txtItemPrice = new javax.swing.JTextField();
        txtItemName = new javax.swing.JTextField();
        txtItemCode = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        lblMainImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton4.setBackground(new java.awt.Color(0, 51, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("_");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton4.setContentAreaFilled(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1270, 10, 40, 30));

        jButton5.setBackground(new java.awt.Color(255, 51, 51));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("X");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jButton5.setContentAreaFilled(false);
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1320, 10, 40, 30));

        jLabel1.setFont(new java.awt.Font("Jura", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Stock Manage");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 420, 90));

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Jura", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Item Code");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 170, 60));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Jura", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Item Name");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 170, 60));

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Jura", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Item Price");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 170, 60));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Jura", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Quntity");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 540, 170, 60));

        btnDelete.setBackground(new java.awt.Color(51, 51, 51));
        btnDelete.setFont(new java.awt.Font("Jura", 1, 24)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.setContentAreaFilled(false);
        btnDelete.setOpaque(true);
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        btnDelete.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnDeleteKeyPressed(evt);
            }
        });
        getContentPane().add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 500, 140, 50));

        txtItemQunti.setFont(new java.awt.Font("Jura", 1, 24)); // NOI18N
        txtItemQunti.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtItemQunti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemQuntiActionPerformed(evt);
            }
        });
        txtItemQunti.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtItemQuntiKeyPressed(evt);
            }
        });
        getContentPane().add(txtItemQunti, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 540, 420, 60));

        txtItemPrice.setFont(new java.awt.Font("Jura", 1, 24)); // NOI18N
        txtItemPrice.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtItemPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemPriceActionPerformed(evt);
            }
        });
        txtItemPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtItemPriceKeyPressed(evt);
            }
        });
        getContentPane().add(txtItemPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 440, 420, 60));

        txtItemName.setFont(new java.awt.Font("Jura", 1, 24)); // NOI18N
        txtItemName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtItemName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtItemNameKeyPressed(evt);
            }
        });
        getContentPane().add(txtItemName, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 340, 420, 60));

        txtItemCode.setFont(new java.awt.Font("Jura", 1, 24)); // NOI18N
        txtItemCode.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtItemCode.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtItemCodeCaretUpdate(evt);
            }
        });
        txtItemCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtItemCodeActionPerformed(evt);
            }
        });
        txtItemCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtItemCodeKeyPressed(evt);
            }
        });
        getContentPane().add(txtItemCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 230, 420, 60));

        btnAdd.setBackground(new java.awt.Color(51, 51, 51));
        btnAdd.setFont(new java.awt.Font("Jura", 1, 24)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.setContentAreaFilled(false);
        btnAdd.setOpaque(true);
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        btnAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnAddKeyPressed(evt);
            }
        });
        getContentPane().add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 290, 140, 50));

        btnUpdate.setBackground(new java.awt.Color(51, 51, 51));
        btnUpdate.setFont(new java.awt.Font("Jura", 1, 24)); // NOI18N
        btnUpdate.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdate.setText("Update");
        btnUpdate.setContentAreaFilled(false);
        btnUpdate.setOpaque(true);
        btnUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpdateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnUpdateMouseEntered(evt);
            }
        });
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        btnUpdate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnUpdateKeyPressed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 400, 140, 50));

        lblMainImage.setBackground(new java.awt.Color(51, 51, 51));
        lblMainImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/foodcitymanagement/icon/5256514-blur-wallpaper.jpg"))); // NOI18N
        getContentPane().add(lblMainImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
            this.dispose();
          
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked

    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        try {
            String itemCode = txtItemCode.getText();
            boolean deleteItem = ItemController.deleteItem(itemCode);
            if (deleteItem) {
                JOptionPane.showMessageDialog(this, "Item Succsesfully Deleted..!");
                txtItemCode.setText(null);
                txtItemName.setText(null);
                txtItemPrice.setText(null);
                txtItemQunti.setText(null);
                txtItemCode.requestFocus(true);
            } else {
                JOptionPane.showMessageDialog(this, "Delete Failed..!");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ItemManageForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ItemManageForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnDeleteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnDeleteKeyPressed
        int keyCode = evt.getKeyCode();
        if (keyCode == KeyEvent.VK_ENTER) {
            btnDelete.doClick();
        }
        if (keyCode == KeyEvent.VK_UP) {
            btnAdd.requestFocus();
        }
        // int keyCode = evt.getKeyCode();
        if (keyCode == KeyEvent.VK_ESCAPE) {
            HomePage.mainPanel.removeAll();
            HomePage.mainPanel.setVisible(false);
        }
    }//GEN-LAST:event_btnDeleteKeyPressed

    private void txtItemQuntiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemQuntiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemQuntiActionPerformed

    private void txtItemQuntiKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemQuntiKeyPressed
        int keyCode = evt.getKeyCode();
        if (keyCode == KeyEvent.VK_UP) {
            txtItemPrice.requestFocus(true);
        }
        if (keyCode == KeyEvent.VK_RIGHT) {
            btnAdd.requestFocus(true);
        }
        //  int keyCode = evt.getKeyCode();
        if (keyCode == KeyEvent.VK_ESCAPE) {
            HomePage.mainPanel.removeAll();
            HomePage.mainPanel.setVisible(false);
        }
    }//GEN-LAST:event_txtItemQuntiKeyPressed

    private void txtItemPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtItemPriceActionPerformed

    private void txtItemPriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemPriceKeyPressed
        int keyCode = evt.getKeyCode();
        if (keyCode == KeyEvent.VK_DOWN) {
            txtItemQunti.requestFocus(true);
        }
        if (keyCode == KeyEvent.VK_UP) {
            txtItemName.requestFocus(true);
        }
        if (keyCode == KeyEvent.VK_RIGHT) {
            btnAdd.requestFocus(true);
        }
        //int keyCode = evt.getKeyCode();
        if (keyCode == KeyEvent.VK_ESCAPE) {
            HomePage.mainPanel.removeAll();
            HomePage.mainPanel.setVisible(false);
        }
    }//GEN-LAST:event_txtItemPriceKeyPressed

    private void txtItemNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemNameKeyPressed
        int keyCode = evt.getKeyCode();
        if (keyCode == KeyEvent.VK_DOWN) {
            txtItemPrice.requestFocus(true);
        }
        if (keyCode == KeyEvent.VK_UP) {
            txtItemCode.requestFocus(true);
        }
        if (keyCode == KeyEvent.VK_RIGHT) {
            btnAdd.requestFocus(true);
        }
        //int keyCode = evt.getKeyCode();
        if (keyCode == KeyEvent.VK_ESCAPE) {
            HomePage.mainPanel.removeAll();
            HomePage.mainPanel.setVisible(false);
        }
    }//GEN-LAST:event_txtItemNameKeyPressed

    private void txtItemCodeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtItemCodeCaretUpdate
        try {
            String itemCode = txtItemCode.getText();

            Item searchItem = ItemController.searchItem(itemCode);
            if (searchItem != null) {
                txtItemName.setText(searchItem.getDescription());
                txtItemPrice.setText(Double.toString(searchItem.getUnitPrice()));
                txtItemQunti.setText(Double.toString(searchItem.getQtyOnHand()));
            } else {

            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ItemManageForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ItemManageForm.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_txtItemCodeCaretUpdate

    private void txtItemCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtItemCodeActionPerformed
        try {
            String itemCode = txtItemCode.getText();

            Item searchItem = ItemController.searchItem(itemCode);
            if (searchItem != null) {
                txtItemName.setText(searchItem.getDescription());
                txtItemPrice.setText(Double.toString(searchItem.getUnitPrice()));
                txtItemQunti.setText(Double.toString(searchItem.getQtyOnHand()));
            } else {
                JOptionPane.showMessageDialog(this, "No Such Item");

            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ItemManageForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ItemManageForm.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_txtItemCodeActionPerformed

    private void txtItemCodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemCodeKeyPressed
        int keyCode = evt.getKeyCode();
        if (keyCode == KeyEvent.VK_DOWN) {
            txtItemName.requestFocus(true);
        }
        if (keyCode == KeyEvent.VK_RIGHT) {
            btnAdd.requestFocus(true);
        }
        // int keyCode = evt.getKeyCode();
        if (keyCode == KeyEvent.VK_ESCAPE) {
            HomePage.mainPanel.removeAll();
            HomePage.mainPanel.setVisible(false);
        }
    }//GEN-LAST:event_txtItemCodeKeyPressed

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked

    }//GEN-LAST:event_btnAddMouseClicked

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        try {
            String itemCode = txtItemCode.getText();
            String itemName = txtItemName.getText();
            double itemPrice = Double.parseDouble(txtItemPrice.getText());
            int itemQuntity = Integer.parseInt(txtItemQunti.getText());

            Item item = new Item(itemCode, itemName, itemPrice, itemQuntity);
            boolean addItem = ItemController.addItem(item);
            if (addItem) {
                JOptionPane.showMessageDialog(this, "Item Succsesfully Aded..!");
                txtItemCode.setText(null);
                txtItemName.setText(null);
                txtItemPrice.setText(null);
                txtItemQunti.setText(null);
                txtItemCode.requestFocus(true);
            } else {
                JOptionPane.showMessageDialog(this, "Aded Failed..!");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ItemManageForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(ItemManageForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnAddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnAddKeyPressed
        int keyCode = evt.getKeyCode();
        if (keyCode == KeyEvent.VK_ENTER) {
            btnAdd.doClick();
        }
        if (keyCode == KeyEvent.VK_DOWN) {
            btnUpdate.requestFocus();
        }
        if (keyCode == KeyEvent.VK_LEFT) {
            txtItemCode.requestFocus();
        }
        // int keyCode = evt.getKeyCode();
        if (keyCode == KeyEvent.VK_ESCAPE) {
            HomePage.mainPanel.removeAll();
            HomePage.mainPanel.setVisible(false);
        }
    }//GEN-LAST:event_btnAddKeyPressed

    private void btnUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseClicked

    }//GEN-LAST:event_btnUpdateMouseClicked

    private void btnUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpdateMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateMouseEntered

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            String itemCode = txtItemCode.getText();
            String itemName = txtItemName.getText();
            double itemPrice = Double.parseDouble(txtItemPrice.getText());
            int itemQuntity = Integer.parseInt(txtItemQunti.getText());

            Item item = new Item(itemCode, itemName, itemPrice, itemQuntity);
            boolean updateItem = ItemController.updateItem(item);
            if (updateItem) {
                JOptionPane.showMessageDialog(this, "Item Succsesfully Updated..!");
                txtItemCode.setText(null);
                txtItemName.setText(null);
                txtItemPrice.setText(null);
                txtItemQunti.setText(null);
                txtItemCode.requestFocus(true);
            } else {
                JOptionPane.showMessageDialog(this, "Update Failed..!");
            }
        } catch (SQLException ex) {
            Logger.getLogger(ItemManageForm.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(ItemManageForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnUpdateKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnUpdateKeyPressed
        int keyCode = evt.getKeyCode();
        if (keyCode == KeyEvent.VK_ENTER) {
            btnUpdate.doClick();
        }
        if (keyCode == KeyEvent.VK_DOWN) {
            btnDelete.requestFocus();
        }
        //  int keyCode = evt.getKeyCode();
        if (keyCode == KeyEvent.VK_ESCAPE) {
            HomePage.mainPanel.removeAll();
            HomePage.mainPanel.setVisible(false);
        }
    }//GEN-LAST:event_btnUpdateKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ItemManageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ItemManageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ItemManageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ItemManageForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ItemManageForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblMainImage;
    private javax.swing.JTextField txtItemCode;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtItemPrice;
    private javax.swing.JTextField txtItemQunti;
    // End of variables declaration//GEN-END:variables
}
