/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.foodcitymanagement.view;

import com.foodcitymanagement.controller.UserController;
import com.foodcitymanagement.dto.User;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.DateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Sanu Vithanage
 */
public class Loging extends javax.swing.JFrame {

    /**
     * Creates new form Loging
     */
    public Loging() {
        initComponents();
        setDate();
        setTime();
        userNameField.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTime = new javax.swing.JLabel();
        labelDate = new javax.swing.JLabel();
        buttonLoging = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        buttonMinimize = new javax.swing.JButton();
        buttonExit = new javax.swing.JButton();
        passWordFiled = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTime.setBackground(new java.awt.Color(255, 255, 255));
        labelTime.setFont(new java.awt.Font("Jura", 0, 36)); // NOI18N
        labelTime.setForeground(new java.awt.Color(255, 255, 255));
        labelTime.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelTime.setText("08:02 PM");
        getContentPane().add(labelTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 70, 230, 40));

        labelDate.setBackground(new java.awt.Color(255, 255, 255));
        labelDate.setFont(new java.awt.Font("Jura", 0, 36)); // NOI18N
        labelDate.setForeground(new java.awt.Color(255, 255, 255));
        labelDate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelDate.setText("2016-08-03");
        getContentPane().add(labelDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 80, 230, 90));

        buttonLoging.setBackground(new java.awt.Color(51, 51, 51));
        buttonLoging.setFont(new java.awt.Font("Jura", 0, 36)); // NOI18N
        buttonLoging.setForeground(new java.awt.Color(255, 255, 255));
        buttonLoging.setText("Loging");
        buttonLoging.setToolTipText("ENTER TO YOUR FOODCITY MANAGEMENT SYSTEM......");
        buttonLoging.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        buttonLoging.setContentAreaFilled(false);
        buttonLoging.setOpaque(true);
        buttonLoging.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLogingMouseClicked(evt);
            }
        });
        buttonLoging.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogingActionPerformed(evt);
            }
        });
        buttonLoging.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                buttonLogingKeyPressed(evt);
            }
        });
        getContentPane().add(buttonLoging, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 580, 500, 60));

        jLabel10.setFont(new java.awt.Font("Jura", 0, 26)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("USERNAME");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 500, 70));

        jLabel11.setFont(new java.awt.Font("Jura", 0, 26)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("PASSWORD");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 430, 500, 60));

        jLabel12.setFont(new java.awt.Font("Jura", 1, 50)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Badi Road Juntion , Labuduwa .");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 820, 70));

        userNameField.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        userNameField.setForeground(new java.awt.Color(102, 102, 102));
        userNameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameFieldFocusGained(evt);
            }
        });
        userNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameFieldActionPerformed(evt);
            }
        });
        userNameField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userNameFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userNameFieldKeyReleased(evt);
            }
        });
        getContentPane().add(userNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 370, 500, 60));

        buttonMinimize.setBackground(new java.awt.Color(0, 51, 153));
        buttonMinimize.setFont(new java.awt.Font("Jura", 1, 18)); // NOI18N
        buttonMinimize.setForeground(new java.awt.Color(255, 255, 255));
        buttonMinimize.setText("_");
        buttonMinimize.setToolTipText("MINIMIZE");
        buttonMinimize.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        buttonMinimize.setContentAreaFilled(false);
        buttonMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMinimizeActionPerformed(evt);
            }
        });
        getContentPane().add(buttonMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 10, 40, 40));

        buttonExit.setBackground(new java.awt.Color(255, 51, 51));
        buttonExit.setFont(new java.awt.Font("Jura", 1, 18)); // NOI18N
        buttonExit.setForeground(new java.awt.Color(255, 255, 255));
        buttonExit.setText("X");
        buttonExit.setToolTipText("EXIT ");
        buttonExit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        buttonExit.setContentAreaFilled(false);
        buttonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonExitActionPerformed(evt);
            }
        });
        getContentPane().add(buttonExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1310, 10, 40, 40));

        passWordFiled.setFont(new java.awt.Font("Verdana", 0, 24)); // NOI18N
        passWordFiled.setForeground(new java.awt.Color(102, 102, 102));
        passWordFiled.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        passWordFiled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passWordFiledActionPerformed(evt);
            }
        });
        passWordFiled.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passWordFiledKeyPressed(evt);
            }
        });
        getContentPane().add(passWordFiled, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 500, 500, 60));

        jLabel9.setFont(new java.awt.Font("Jura", 1, 50)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Private Ltd.");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, 820, 70));

        jLabel8.setFont(new java.awt.Font("Jura", 1, 50)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("PRADEEP GROCERY");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 120, 820, 90));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/foodcitymanagement/icon/5256514-blur-wallpaper.jpg"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMinimizeActionPerformed
        setState(ICONIFIED);
    }//GEN-LAST:event_buttonMinimizeActionPerformed

    private void buttonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonExitActionPerformed
        QuitForm form = new QuitForm();
        form.setVisible(true);
    }//GEN-LAST:event_buttonExitActionPerformed

    private void buttonLogingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogingActionPerformed
        loginToSystem();
    }//GEN-LAST:event_buttonLogingActionPerformed

    private void buttonLogingKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buttonLogingKeyPressed
        loginToSystem();
    }//GEN-LAST:event_buttonLogingKeyPressed

    private void userNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameFieldFocusGained

    }//GEN-LAST:event_userNameFieldFocusGained

    private void userNameFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameFieldKeyReleased

    }//GEN-LAST:event_userNameFieldKeyReleased

    private void userNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameFieldActionPerformed
        passWordFiled.requestFocus();
    }//GEN-LAST:event_userNameFieldActionPerformed

    private void passWordFiledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passWordFiledActionPerformed
        buttonLoging.requestFocus();
    }//GEN-LAST:event_passWordFiledActionPerformed

    private void userNameFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameFieldKeyPressed
        int keyCode = evt.getKeyCode();
        if (keyCode == KeyEvent.VK_DOWN) {
            passWordFiled.requestFocus(true);
        }

    }//GEN-LAST:event_userNameFieldKeyPressed

    private void passWordFiledKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passWordFiledKeyPressed
        int keyCode = evt.getKeyCode();
        if (keyCode == KeyEvent.VK_UP) {
            userNameField.requestFocus(true);
        }
    }//GEN-LAST:event_passWordFiledKeyPressed

    private void buttonLogingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLogingMouseClicked
        loginToSystem();
    }//GEN-LAST:event_buttonLogingMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loging.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loging().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonExit;
    private javax.swing.JButton buttonLoging;
    private javax.swing.JButton buttonMinimize;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelDate;
    private javax.swing.JLabel labelTime;
    private javax.swing.JPasswordField passWordFiled;
    private javax.swing.JTextField userNameField;
    // End of variables declaration//GEN-END:variables

    private void setDate() {
        Date today = new Date();
        labelDate.setText(DateFormat.getDateInstance().format(today));
    }
    int timeRun = 0;

    private void setTime() {
        new Thread() {
            public void run() {
                while (timeRun == 0) {
                    Calendar calendar = new GregorianCalendar();
                    int second = calendar.get(Calendar.SECOND);
                    int minute = calendar.get(Calendar.MINUTE);
                    int hour = calendar.get(Calendar.HOUR);
                    int am_pm = calendar.get(Calendar.AM_PM);

                    String day_night = "";
                    if (am_pm == 1) {
                        day_night = "PM";
                    } else {
                        day_night = "AM";
                    }

                    labelTime.setText(hour + ":" + minute + ":" + second + ":" + day_night);
                }

            }

        }.start();

    }

    private void loginToSystem() {
        try {
            String userName = userNameField.getText();
            String passW = passWordFiled.getText();

            User searchItem = UserController.searchItem(userName);
            if (searchItem != null) {
                if (searchItem.getUserPass().equals(passW) && searchItem.getUserName().equals(userName)) {
                    this.dispose();
                    new HomePage().setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Wrong PassWord..!");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Check Your UserName..!");
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Loging.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Loging.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
